phase3 trasit gate way apply

diff --git a/.github/workflows/phase3-hub.yaml b/.github/workflows/phase3-hub.yaml
--- a/.github/workflows/phase3-hub.yaml
+++ b/.github/workflows/phase3-hub.yaml
@@ -25,20 +25,30 @@ jobs:
         working-directory: terraform/phase3-hub
 
     steps:
+
       - name: Checkout
         uses: actions/checkout@v4
 
+      # ------------------------------------------------
+      # AWS OIDC
+      # ------------------------------------------------
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
           role-to-assume: arn:aws:iam::878962827886:role/Rajesh-devops
           aws-region: ap-south-1
 
+      # ------------------------------------------------
+      # Verify AWS
+      # ------------------------------------------------
       - name: Verify AWS Identity
         run: |
           aws sts get-caller-identity
           aws ec2 describe-vpcs --region ap-south-1
 
+      # ------------------------------------------------
+      # Check Terraform State Bucket
+      # ------------------------------------------------
       - name: Check Terraform State Bucket
         run: |
           aws s3api head-bucket \
@@ -47,6 +57,29 @@ jobs:
           aws s3 ls \
             s3://rajesh-terraform-state-878962827886
 
+      # ------------------------------------------------
+      # Check Required Variables
+      # ------------------------------------------------
+      - name: Check Required Variables
+        env:
+          TRANSIT_GATEWAY_ID: ${{ vars.TRANSIT_GATEWAY_ID }}
+          SPOKE_ACCOUNT_ID: ${{ vars.SPOKE_ACCOUNT_ID }}
+        run: |
+          if [ -z "$TRANSIT_GATEWAY_ID" ]; then
+            echo "ERROR: TRANSIT_GATEWAY_ID GitHub variable is missing"
+            exit 1
+          fi
+
+          if [ -z "$SPOKE_ACCOUNT_ID" ]; then
+            echo "ERROR: SPOKE_ACCOUNT_ID GitHub variable is missing"
+            exit 1
+          fi
+
+          echo "Required variables are configured."
+
+      # ------------------------------------------------
+      # Terraform
+      # ------------------------------------------------
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3
         with:
@@ -59,7 +92,15 @@ jobs:
         run: terraform validate
 
       - name: Terraform Plan
-        run: terraform plan -out=tfplan -input=false
+        env:
+          TF_VAR_transit_gateway_id: ${{ vars.TRANSIT_GATEWAY_ID }}
+          TF_VAR_spoke_account_id: ${{ vars.SPOKE_ACCOUNT_ID }}
+        run: |
+          terraform plan -out=tfplan -input=false
 
       - name: Terraform Apply
-        run: terraform apply -auto-approve tfplan          
+        env:
+          TF_VAR_transit_gateway_id: ${{ vars.TRANSIT_GATEWAY_ID }}
+          TF_VAR_spoke_account_id: ${{ vars.SPOKE_ACCOUNT_ID }}
+        run: |
+          terraform apply -auto-approve tfplan   
