phase3 all apply

diff --git a/.github/workflows/phase3-spoke.yaml b/.github/workflows/phase3-spoke.yaml
--- a/.github/workflows/phase3-spoke.yaml
+++ b/.github/workflows/phase3-spoke.yaml
@@ -13,7 +13,7 @@ on:
 
 permissions:
   id-token: write
-  contents: read 
+  contents: read
 
 jobs:
   phase3-spoke:
@@ -32,7 +32,7 @@ jobs:
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v6
         with:
-          role-to-assume: arn:aws:iam::434097521299:role/testingdummy  
+          role-to-assume: arn:aws:iam::434097521299:role/testingdummy
           aws-region: ap-south-1
 
       - name: Check AWS identity
@@ -41,6 +41,45 @@ jobs:
 
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3
+
+      - name: Check required variables
+        run: |
+          if [ -z "${{ vars.AWS_REGION }}" ]; then
+            echo "ERROR: AWS_REGION is missing"
+            exit 1
+          fi
+
+          if [ -z "${{ vars.TRANSIT_GATEWAY_ID }}" ]; then
+            echo "ERROR: TRANSIT_GATEWAY_ID is missing"
+            exit 1
+          fi
+
+          if [ -z "${{ vars.SPOKE_VPC_ID }}" ]; then
+            echo "ERROR: SPOKE_VPC_ID is missing"
+            exit 1
+          fi
+
+          if [ -z "${{ vars.SPOKE_PRIVATE_SUBNET_1 }}" ]; then
+            echo "ERROR: SPOKE_PRIVATE_SUBNET_1 is missing"
+            exit 1
+          fi
+
+          if [ -z "${{ vars.SPOKE_PRIVATE_SUBNET_2 }}" ]; then
+            echo "ERROR: SPOKE_PRIVATE_SUBNET_2 is missing"
+            exit 1
+          fi
+
+          if [ -z "${{ vars.SPOKE_ROUTE_TABLE_1 }}" ]; then
+            echo "ERROR: SPOKE_ROUTE_TABLE_1 is missing"
+            exit 1
+          fi
+
+          if [ -z "${{ vars.SPOKE_ROUTE_TABLE_2 }}" ]; then
+            echo "ERROR: SPOKE_ROUTE_TABLE_2 is missing"
+            exit 1
+          fi
+
+          echo "All required variables are configured."
 
       - name: Create terraform.tfvars
         run: |
@@ -66,14 +105,21 @@ jobs:
           spoke_vpc_cidr = "10.1.0.0/16"
           EOF
 
+      - name: Show terraform.tfvars
+        run: |
+          cat terraform.tfvars
+
+      - name: Terraform Format
+        run: terraform fmt -check
+
       - name: Terraform Init
-        run: terraform init
+        run: terraform init -input=false
 
       - name: Terraform Validate
         run: terraform validate
 
       - name: Terraform Plan
-        run: terraform plan
+        run: terraform plan -input=false -var-file="terraform.tfvars"
 
       - name: Terraform Apply
-        run: terraform apply -auto-approve 
+        run: terraform apply -input=false -auto-approve -var-file="terraform.tfvars"  
