phase3 trasit gate way apply

diff --git a/.github/workflows/phase3-hub.yaml b/.github/workflows/phase3-hub.yaml
--- a/.github/workflows/phase3-hub.yaml
+++ b/.github/workflows/phase3-hub.yaml
@@ -26,31 +26,37 @@ jobs:
 
     steps:
 
-      # --------------------------------
-      # Checkout
-      # --------------------------------
       - name: Checkout
         uses: actions/checkout@v4
 
-      # --------------------------------
-      # AWS OIDC
-      # --------------------------------
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
           role-to-assume: arn:aws:iam::878962827886:role/Rajesh-devops
           aws-region: ap-south-1
 
-      # --------------------------------
-      # Verify AWS Account
-      # --------------------------------
       - name: Verify AWS Identity
         run: |
           aws sts get-caller-identity
 
-      # --------------------------------
-      # Check Terraform State Bucket
-      # --------------------------------
+      # Get TGW ID automatically from Hub
+      - name: Get Transit Gateway ID
+        id: tgw
+        run: |
+          TGW_ID=$(aws ec2 describe-transit-gateways \
+            --region ap-south-1 \
+            --query 'TransitGateways[?State==`available`].TransitGatewayId | [0]' \
+            --output text)
+
+          if [ -z "$TGW_ID" ] || [ "$TGW_ID" = "None" ]; then
+            echo "ERROR: No available Transit Gateway found in Hub account"
+            exit 1
+          fi
+
+          echo "Transit Gateway found"
+
+          echo "transit_gateway_id=$TGW_ID" >> "$GITHUB_OUTPUT"
+
       - name: Check Terraform State Bucket
         run: |
           aws s3api head-bucket \
@@ -59,69 +65,34 @@ jobs:
           aws s3 ls \
             s3://rajesh-terraform-state-878962827886
 
-      # --------------------------------
-      # Check Required Variables
-      # --------------------------------
-      - name: Check Required Variables
-        env:
-          TRANSIT_GATEWAY_ID: ${{ vars.TRANSIT_GATEWAY_ID }}
-          SPOKE_ACCOUNT_ID: ${{ vars.SPOKE_ACCOUNT_ID }}
-        run: |
-          if [ -z "$TRANSIT_GATEWAY_ID" ]; then
-            echo "ERROR: TRANSIT_GATEWAY_ID GitHub repository variable is missing"
-            exit 1
-          fi
-
-          if [ -z "$SPOKE_ACCOUNT_ID" ]; then
-            echo "ERROR: SPOKE_ACCOUNT_ID GitHub repository variable is missing"
-            exit 1
-          fi
-
-          echo "Required GitHub variables are configured."
-
-      # --------------------------------
-      # Setup Terraform
-      # --------------------------------
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3
         with:
           terraform_version: 1.13.3
 
-      # --------------------------------
-      # Terraform Init
-      # --------------------------------
       - name: Terraform Init
         run: |
           terraform init -reconfigure -input=false
 
-      # --------------------------------
-      # Terraform Validate
-      # --------------------------------
       - name: Terraform Validate
         run: |
           terraform validate
 
-      # --------------------------------
-      # Terraform Plan
-      # --------------------------------
       - name: Terraform Plan
         env:
-          TF_VAR_transit_gateway_id: ${{ vars.TRANSIT_GATEWAY_ID }}
+          TF_VAR_transit_gateway_id: ${{ steps.tgw.outputs.transit_gateway_id }}
           TF_VAR_spoke_account_id: ${{ vars.SPOKE_ACCOUNT_ID }}
         run: |
           terraform plan \
             -input=false \
             -out=tfplan
 
-      # --------------------------------
-      # Terraform Apply
-      # --------------------------------
       - name: Terraform Apply
         env:
-          TF_VAR_transit_gateway_id: ${{ vars.TRANSIT_GATEWAY_ID }}
+          TF_VAR_transit_gateway_id: ${{ steps.tgw.outputs.transit_gateway_id }}
           TF_VAR_spoke_account_id: ${{ vars.SPOKE_ACCOUNT_ID }}
         run: |
           terraform apply \
             -input=false \
             -auto-approve \
-            tfplan   
+            tfplan 
